
development:
  adapter: postgresql
  database: entitled_dev
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  database: entitled_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: entitled_production
  pool: 5
  timeout: 5000
