
development:
  adapter: postgresql
  host: localhost
  database: entitle_dev
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  host: localhost
  database: entitle_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: entitle_production
  host: localhost
  pool: 5
  timeout: 5000